### ISSUE TITLE
Unwanted __pycache__

### ISSUE THREAD

**Issue by S-art-stack** [mursalatul/github-doc-gen#1]
pycache is automatically generating after the action executing UPDATE_DOC.py. It not not needed after updating the documentation process.
![image_2024-02-25_03-01-45](https://github.com/mursalatul/github-doc-gen/assets/91667875/91235019-4190-41f7-b5a7-0ea72fb706c0)

**Comment by mursalatul** [comment]
if you can, please fix it.
